---
apiVersion: v1
kind: Service
metadata:
  name: character-service
  namespace: onepiece
  labels:
    app: character-service
spec:
  selector:
    app: character-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
  type: ClusterIP
