---
apiVersion: v1
kind: Namespace
metadata:
  name: onepiece
  labels:
    app: onepiece
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: onepiece-monitoring
  labels:
    app: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: onepiece-gateway
  labels:
    app: gateway
